apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pv-protection
  name: rsyncer-pv
  selfLink: /api/v1/persistentvolumes/crunchy-volume-replica
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /exports/backup
    server: ocp-nexica-bastion.uoc.es
  persistentVolumeReclaimPolicy: Retain
  storageClassName: legacy-nfs
status: {}
