apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
  namespace: oc-rsyncer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-backup-sacc
subjects:
  - kind: ServiceAccount
    name: backup
    namespace: oc-rsyncer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

